<?php
$countries = [
    'ALBANIA',
    'BULGARIA',
    'CANADA',
    'DENMARK',
    'EGYPT',
    'FRANCE',
    'GREENLAND',
    'HUNGARY',
    'ICELAND',
    'JAPAN',
    'KOREA',
    'LIECHTENSTEIN',
    'MEXICO',
    'NEW ZEALAND',
    'OMAN',
    'PERU',
    'QATAR',
    'ROMANIA',
    'SWEDEN',
    'TURKEY',
    'UNITED KINGDOM',
    'VENEZUELA',
    'MEXICO',
    'WALLIS AND FUTUNA',
    'YEMEN',
    'ZIMBABWE',
];